# Generated by Django 3.2.23 on 2024-02-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = []
